name: Auto release using standard-version
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure committer
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<arkadiusz.noster@gmail.com>"
    - name: Bump version
      uses: qzb/standard-version@v1
